### ISSUE TITLE
Prevents Jenkins from auto-creating workspace directory on a clean build slave

### ISSUE THREAD

**Issue by nurupo** [tux3/jenkins-autoarmor#9]
When adding a new node in Jenkins, you have to specify the root path. The workspace directory is then located at `/root-path/workspace`.

The issue is that on a cleanly built slave with no apparmor plugin installed, Jenkins will create the `/root-path/workspace` itself, but with this plugin installed, Jenkins will fail to create the `/root-path/workspace` and any job running would fail with the following error

```
Started by user <USERNAME>
Autoarmor: Loading AppArmor profile for workspace /root-path/workspace/<JOB_NAME>
FATAL: Autoarmor: Failed to load AppArmor profile, cancelling build.
java.lang.RuntimeException: Autoarmor: Failed to load AppArmor profile, cancelling build.
    at chat.tox.jenkins.autoarmor.AutoarmorLauncherDecorator.decorate(AutoarmorLauncherDecorator.java:109)
    at hudson.Launcher.decorateFor(Launcher.java:694)
    at hudson.model.Slave.createLauncher(Slave.java:387)
    at hudson.model.AbstractBuild$AbstractBuildExecution.createLauncher(AbstractBuild.java:561)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:492)
    at hudson.model.Run.execute(Run.java:1738)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Finished: FAILURE
```

With the plugin enabled, Jenkins successfully creates `/root-path`, but doesn't create `workspace` in it. I think the plugin fails with the above error because it gives `genprof` job path `/root-path/workspace/<JOB_NAME>`, which doesn't exist because `workspace` directory wasn't auto-created by Jenkins. Disabling the plugin in Jenkins settings fixes the issue, Jenkins becomes able to create `workspace` directory and the job succeeds. Once the `workspace` directory is created, all consecutive jobs succeed too.

The current workaround I use is to `mkdir -p /root-path/workspace`, instead of relying on Jenkins to create it.

**Comment by tux3** [comment]
A possible fix could be to have genprof ensure the workspace exists when creating the profile
I'm not sure if it's possible to safely give any jobs the permission to create the workspace as needed, without accidentally giving them permission to delete the whole workspace or tamper with other jobs.
